# Generated by Django 4.0.3 on 2022-03-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancers',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='profesionales',
            name='usuario_ptr',
        ),
        migrations.DeleteModel(
            name='estudiantes',
        ),
        migrations.DeleteModel(
            name='freelancers',
        ),
        migrations.DeleteModel(
            name='profesionales',
        ),
    ]
