# Generated by Django 4.0.3 on 2022-04-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_blog_mensaje_remove_freelancers_usuario_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='material',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
