# Generated by Django 4.0.3 on 2022-04-15 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='material',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
