# Generated by Django 4.0.3 on 2022-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='material',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
