# Generated by Django 4.0.3 on 2022-04-16 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 13, 37, 30, 175744, tzinfo=utc)),
        ),
    ]
