# Generated by Django 4.0.3 on 2022-04-16 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 13, 38, 59, 154291, tzinfo=utc)),
        ),
    ]
